id: P009267
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG16805
  title: མངའ་རིས་གསེར་རྫོང་།
  author: ''
  volumes:
    bf678faac20a43dc9ed5a264c3504e72:
      image_group_id: I1KG17045
      title: ''
      volume_number: 1
      total_pages: 614
      base_file: v001.txt
